from agent import setup_agent
from langchain_core.messages import HumanMessage
import os

agent = setup_agent()
msg = HumanMessage(content="What is the price of AAPL?")

# Let's inspect the stream payloads natively generated by langgraph
try:
    for chunk in agent.stream({"messages": [msg]}, stream_mode="messages"):
        # chunk is a tuple: (message_chunk, metadata_dict)
        msg_chunk, metadata = chunk
        print(f"Type: {type(msg_chunk).__name__}, Content: {msg_chunk.content[:20]}..., Tool Calls: {getattr(msg_chunk, 'tool_calls', None)}")
except Exception as e:
    print(f"Error: {e}")
